---
title: "PCoA and PERMANOVA"
output:
    html_document:
        toc: false
        toc_float: true
---

```{r include=FALSE}
library(phyloseq)
library(tidyverse)
library(vegan)
```

```{r include=FALSE}
#Deal with some annoying Snakemake behavior.
#This script will be run in the working directory containing this script. Strange but true.
#Leave absolute paths alone, change relative paths to reflect this
ps.file <- snakemake@input[['rds']]
ps.file <- ifelse(grepl("^/",ps.file),ps.file,paste0("../",ps.file))
ps <- readRDS(ps.file)
```

```{r include=FALSE}
ps.rar <- rarefy_even_depth(ps,rngseed = 1)
rarefy_size <- min(sample_sums(ps.rar))
```

Rarefying OTU table to `r prettyNum(rarefy_size,big.mark=",",scientific=FALSE)` reads per sample.

```{r include=FALSE}
plot.pcoa <- function(ps.obj,distance.measure='bray'){
    ord <- ordinate(ps.obj,method='PCoA',distance=distance.measure)
    var.strings <- paste0('Axis ',c('1','2'),' (',round(100*ord$values$Relative_eig[1:2],digits=1),'%)')
    data.frame(
        sample_data(ps),
        ord$vectors
    ) %>%
        ggplot(aes_string('Axis.1','Axis.2',color=snakemake@config$pcoa$color_attribute)) + geom_point(size=3) +
        xlab(var.strings[1]) + ylab(var.strings[2]) +
        theme(axis.text = element_text(size=12),axis.title=element_text(size=12))
}
#codetools::findGlobals(plot.pcoa)
```

```{r include=FALSE}
permanova.test <- function(ps.obj,dist.measure,perms=50000,test.var){
    if(dist.measure=='jaccard'){
        dist.obj <- distance(ps.obj,method='jaccard',binary=TRUE)
    } else {
        dist.obj <- distance(ps.obj,method=dist.measure)
    }
    res <- adonis(as.formula(paste0("dist.obj ~ ",test.var)),
                  data=data.frame(sample_data(ps.obj)),permutations = perms)
    res
}
#codetools::findGlobals(permanova.test)
permanova.var <- snakemake@config$pcoa$permanova_attribute
```


## Bray-Curtis dissimilarity

```{r echo=FALSE}
plot.pcoa(ps.rar,'bray')
```

PERMANOVA test:

```{r echo=FALSE}
permanova.test(ps.rar,dist.measure='bray',perms=50000,test.var=permanova.var)
```


## Jensen-Shannon

```{r echo=FALSE}
plot.pcoa(ps.rar,'jsd')
```

PERMANOVA test:

```{r echo=FALSE}
permanova.test(ps.rar,dist.measure='jsd',perms=50000,test.var=permanova.var)
```

## UniFrac

```{r echo=FALSE}
plot.pcoa(ps.rar,'unifrac')
```

PERMANOVA test:

```{r echo=FALSE}
permanova.test(ps.rar,dist.measure='unifrac',perms=50000,test.var=permanova.var)
```

## Weighted UniFrac

```{r echo=FALSE}
plot.pcoa(ps.rar,'wunifrac')
```
PERMANOVA test:

```{r echo=FALSE}
permanova.test(ps.rar,dist.measure='wunifrac',perms=50000,test.var=permanova.var)
```