---
title: "PCoA"
output: 
  flexdashboard::flex_dashboard
---

```{r include=FALSE}
library(pander)
library(vegan)
library(plotly)
library(phyloseq)
```

```{r include=FALSE}
plan_name <- snakemake@wildcards[['plan']]
plan <- snakemake@config$pcoa_plots[[plan_name]]
permanova_formula <- plan$PERMANOVA
permanova_permutations <- plan$PERMANOVA_permutations
```

```{r include=FALSE}
ps.rar <- readRDS(snakemake@input[['ps']])
dropped.samples <- attr(ps.rar,"dropped_samples")
min_reads <- snakemake@config$min_reads
rar.depth <- min(sample_sums(ps.rar))
```


Plots
=====================================

OTU table was rarefied to a depth of `r prettyNum(rar.depth,big.mark=',',scientific=F)`.

```{r echo=FALSE,results='asis'}
if(length(dropped.samples) > 0){
  cat(paste0("The following samples were dropped because they had fewer than ",prettyNum(min_reads,scientific=F,big.mark=',')," total reads:\n\n"))
  formatted <- paste0('`',dropped.samples,'`')
  cat(paste0(
    paste(formatted,collapse = ', '),
    '\n\n'
    )
  )
}
```


## {.tabset}

### Bray-Curtis

#### Plot

```{r include=FALSE}
measure <- 'bray'
```

```{r echo=FALSE,fig.width=8,fig.height=6}
g <- readRDS(snakemake@input[[paste0('pcoa_',measure)]])
ggplotly(g)
```

```{r echo=FALSE,results='asis'}
cat(paste0("\n\nFigure saved as `figures/PCoA/",plan_name,"/BrayCurtis.pdf`"))
```

#### PERMANOVA test:

```{r echo=FALSE,results='asis'}
cat(paste0("Formula: `distance ",gsub("~","~ ",permanova_formula),"`\n\n"))
cat(paste0("Permutations: ",prettyNum(permanova_permutations,big.mark = ',',scientific=F),"\n"))
```

```{r echo=FALSE}
print(readRDS(snakemake@input[[paste0('PERMANOVA_',measure)]]))
```

### Binary Jaccard

#### Plot

```{r include=FALSE}
measure <- 'jaccard'
```

```{r echo=FALSE,fig.width=8,fig.height=6}
g <- readRDS(snakemake@input[[paste0('pcoa_',measure)]])
ggplotly(g)
```

```{r echo=FALSE,results='asis'}
cat(paste0("\n\nFigure saved as `figures/PCoA/",plan_name,"/BinaryJaccard.pdf`"))
```

#### PERMANOVA test:

```{r echo=FALSE,results='asis'}
cat(paste0("Formula: `distance ",gsub("~","~ ",permanova_formula),"`\n\n"))
cat(paste0("Permutations: ",prettyNum(permanova_permutations,big.mark = ',',scientific=F),"\n"))
```

```{r echo=FALSE}
print(readRDS(snakemake@input[[paste0('PERMANOVA_',measure)]]))
```

### UniFrac

#### Plot

```{r include=FALSE}
measure <- 'unifrac'
```

```{r echo=FALSE,fig.width=8,fig.height=6}
g <- readRDS(snakemake@input[[paste0('pcoa_',measure)]])
ggplotly(g)
```

```{r echo=FALSE,results='asis'}
cat(paste0("\n\nFigure saved as `figures/PCoA/",plan_name,"/UniFrac.pdf`"))
```

#### PERMANOVA test:

```{r echo=FALSE,results='asis'}
cat(paste0("Formula: `distance ",gsub("~","~ ",permanova_formula),"`\n\n"))
cat(paste0("Permutations: ",prettyNum(permanova_permutations,big.mark = ',',scientific=F),"\n"))
```

```{r echo=FALSE}
print(readRDS(snakemake@input[[paste0('PERMANOVA_',measure)]]))
```

### Weighted UniFrac

#### Plot

```{r include=FALSE}
measure <- 'wunifrac'
```

```{r echo=FALSE,fig.width=8,fig.height=6}
g <- readRDS(snakemake@input[[paste0('pcoa_',measure)]])
ggplotly(g)
```

```{r echo=FALSE,results='asis'}
cat(paste0("\n\nFigure saved as `figures/PCoA/",plan_name,"/WeightedUniFrac.pdf`"))
```

#### PERMANOVA test:

```{r echo=FALSE,results='asis'}
cat(paste0("Formula: `distance ",gsub("~","~ ",permanova_formula),"`\n\n"))
cat(paste0("Permutations: ",prettyNum(permanova_permutations,big.mark = ',',scientific=F),"\n"))
```

```{r echo=FALSE}
print(readRDS(snakemake@input[[paste0('PERMANOVA_',measure)]]))
```

<!--Include software version info-->

```{r include=FALSE}
absolute.path <- file.path(getwd(),'scripts','SoftwareInfo.Rmd')
```

```{r child=absolute.path}
```