---
title: "Taxonomy Barplots"
output: 
  flexdashboard::flex_dashboard
---

```{r include=FALSE}
#library(tidyverse)
library(plotly)
library(pander)
```

```{r include=FALSE}
plan_name <- snakemake@wildcards[['plan']]
```

Plots
=====================================

## {.tabset}

```{r include=FALSE}
rank <- 'Genus'
```

### `r rank`

#### Plot

```{r echo=FALSE,fig.width=8,fig.height=6}
ggplotly(readRDS(snakemake@input[[rank]]))
```

#### PDF

```{r echo=FALSE,results='asis'}
cat(paste0("\n\nFigure saved as `figures/TaxonomyBarplots/",plan_name,"/",rank,".pdf`"))
```

```{r include=FALSE}
rank <- 'Family'
```

### `r rank`

#### Plot

```{r echo=FALSE,fig.width=8,fig.height=6}
ggplotly(readRDS(snakemake@input[[rank]]))
```

#### PDF

```{r echo=FALSE,results='asis'}
cat(paste0("\n\nFigure saved as `figures/TaxonomyBarplots/",plan_name,"/",rank,".pdf`"))
```

```{r include=FALSE}
rank <- 'Order'
```

### `r rank`

#### Plot

```{r echo=FALSE,fig.width=8,fig.height=6}
ggplotly(readRDS(snakemake@input[[rank]]))
```

#### PDF

```{r echo=FALSE,results='asis'}
cat(paste0("\n\nFigure saved as `figures/TaxonomyBarplots/",plan_name,"/",rank,".pdf`"))
```

```{r include=FALSE}
rank <- 'Class'
```

### `r rank`

#### Plot

```{r echo=FALSE,fig.width=8,fig.height=6}
ggplotly(readRDS(snakemake@input[[rank]]))
```

#### PDF

```{r echo=FALSE,results='asis'}
cat(paste0("\n\nFigure saved as `figures/TaxonomyBarplots/",plan_name,"/",rank,".pdf`"))
```

```{r include=FALSE}
rank <- 'Phylum'
```

### `r rank`

#### Plot

```{r echo=FALSE,fig.width=8,fig.height=6}
ggplotly(readRDS(snakemake@input[[rank]]))
```

#### PDF

```{r echo=FALSE,results='asis'}
cat(paste0("\n\nFigure saved as `figures/TaxonomyBarplots/",plan_name,"/",rank,".pdf`"))
```


Software info
=====================================

## {.tabset}

### R session info

```{r echo=FALSE,results='asis'}
pander(sessionInfo())
```

### Analysis workflow

This report was generated by the [`amplicon_snakemake`](https://github.com/gputzel/amplicon_snakemake) workflow.

Workflow version (git repository checksum):

`r system("git rev-parse HEAD", intern = TRUE)`

